/**
 * GetContribution DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contributions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetContributionParams } from "@shapemint/core/contributions";

export function createGetContributionRequest(overrides: Partial<GetContributionParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
