/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocols
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Protocols Domain Use Cases
 * 
 * List of all use case names for the protocols domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const PROTOCOLS_USE_CASES = [
  "executeBindProtocolToModel",
  "executeCreateProtocol",
  "executeDeprecateProtocol",
  "executeGetProtocol",
  "executeListProtocols",
  "executePublishProtocol"
] as const;
