/**
 * CreateIncentive DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { ulid } from "ulid";
import type { IncentiveMintRequest } from "@shapemint/core/incentives";
import { incentivesSchemas } from "@shapemint/core/incentives";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "inc";

export function createCreateIncentiveRequest(overrides: Partial<IncentiveMintRequest> = {}) {
  const raw = {
    contributionId: overrides.contributionId ?? `ctr_${ulid().toLowerCase()}`,
    influenceScoreId: overrides.influenceScoreId ?? `inf_${ulid().toLowerCase()}`,
    policyId: overrides.policyId ?? `pol_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return incentivesSchemas.IncentiveMintRequest.parse(raw);
}
