/**
 * SettlementStatement Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/incentives.openapi.types.js";
import { schemas } from "../schemas/incentives.schemas.js";

/**
 * Entity: SettlementStatementEntity
 * Description: Represents the SettlementStatement domain model.
 * Source: schemas.SettlementStatement
 * Type: Domain Entity (API)
 */
export const SettlementStatementEntitySchema = schemas.SettlementStatement;
export type SettlementStatementEntity = components["schemas"]["SettlementStatement"];
