/**
 * MintingPause Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { MintingPauseEntity } from "@shapemint/core/governance/models/index.js";
import { governanceSchemas } from "@shapemint/core/governance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "gov";

export function createMintingPause(overrides: Partial<MintingPauseEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    active: overrides.active ?? faker.datatype.boolean(),
    modelId: overrides.modelId ?? `mdl_${ulid().toLowerCase()}`,
    pauseId: overrides.pauseId ?? `pse_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return governanceSchemas.MintingPause.parse(raw);
}

export function mintingPauseBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createMintingPause(overrides));
}
