/**
 * ReproducePack Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: influence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ReproducePackEntity } from "@shapemint/core/influence/models/index.js";
import { influenceSchemas } from "@shapemint/core/influence";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "inf";

export function createReproducePack(overrides: Partial<ReproducePackEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    aggregateMetrics: overrides.aggregateMetrics ?? {},
    attestationHashes: overrides.attestationHashes ?? [],
    generatedAt: overrides.generatedAt ?? new Date().toISOString(),
    influenceScoreId: overrides.influenceScoreId ?? `inf_${ulid().toLowerCase()}`,
    protocolId: overrides.protocolId ?? `prt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return influenceSchemas.ReproducePack.parse(raw);
}

export function reproducePackBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createReproducePack(overrides));
}
