/**
 * Models DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Models Domain Module - Composition root
 *
 * DDD: Composition root for models domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  VModelRepositoryAdapter,
} from "@shapemint/adapters/models";
import { getIdGeneratorService } from "@shapemint/adapters";
import type { AdapterDynamoDBClient } from "@shapemint/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateModel,
  ExecuteGetModel,
  ExecuteListModels,
  ExecuteUpdateModel,
} from "@shapemint/services/models/usecases";
// Ports (interfaces)
import type {
  VModelRepository,
} from "@shapemint/services/models/ports";

export interface ModelsDomainModule {
  repos: {
    vModels: VModelRepository;
  };
  useCases: {
    vModels: {
      create: ExecuteCreateModel;
      get: ExecuteGetModel;
      list: ExecuteListModels;
      update: ExecuteUpdateModel;
    };
  };
}

export function buildModelsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ModelsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      vModels?: VModelRepository;
    } = {};

    obj.vModels = new VModelRepositoryAdapter(dynamoClient);
    return {
      vModels: obj.vModels!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    vModels: {
      create: new ExecuteCreateModel(executionContext, idGenerator, repos.vModels),
      get: new ExecuteGetModel(executionContext, idGenerator, repos.vModels),
      list: new ExecuteListModels(executionContext, idGenerator, repos.vModels),
      update: new ExecuteUpdateModel(executionContext, idGenerator, repos.vModels),
    },
  };
  return { repos, useCases: useCases as ModelsDomainModule["useCases"] };
}
