/**
 * IncentivePolicyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IncentivePolicyRepository Port
 *
 * DDD: Application port for incentivepolicyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateIncentivePolicyInput, CreateIncentivePolicyOutput, GetIncentivePolicyInput, GetIncentivePolicyOutput, ListIncentivePoliciesInput, ListIncentivePoliciesOutput } from "../dto/incentive-policy.dto";
export interface IncentivePolicyRepository {
  listIncentivePolicies(input: ListIncentivePoliciesInput): Promise<ListIncentivePoliciesOutput>;
  createIncentivePolicy(input: CreateIncentivePolicyInput): Promise<CreateIncentivePolicyOutput>;
  getIncentivePolicy(input: GetIncentivePolicyInput): Promise<GetIncentivePolicyOutput>;
}

export type { CreateIncentivePolicyInput, CreateIncentivePolicyOutput, GetIncentivePolicyInput, GetIncentivePolicyOutput, ListIncentivePoliciesInput, ListIncentivePoliciesOutput } from "../dto/incentive-policy.dto";
