/**
 * SettlementStatementRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SettlementStatementRepository Port
 *
 * DDD: Application port for settlementstatementrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateSettlementStatementInput, CreateSettlementStatementOutput, GetSettlementStatementInput, GetSettlementStatementOutput, ListSettlementStatementsInput, ListSettlementStatementsOutput } from "../dto/settlement-statement.dto";
export interface SettlementStatementRepository {
  listSettlementStatements(input: ListSettlementStatementsInput): Promise<ListSettlementStatementsOutput>;
  createSettlementStatement(input: CreateSettlementStatementInput): Promise<CreateSettlementStatementOutput>;
  getSettlementStatement(input: GetSettlementStatementInput): Promise<GetSettlementStatementOutput>;
}

export type { CreateSettlementStatementInput, CreateSettlementStatementOutput, GetSettlementStatementInput, GetSettlementStatementOutput, ListSettlementStatementsInput, ListSettlementStatementsOutput } from "../dto/settlement-statement.dto";
