/**
 * CreateAccept DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: influence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { AcceptInfluenceParams } from "@shapemint/core/influence";

export function createCreateAcceptRequest(overrides: Partial<AcceptInfluenceParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
