/**
 * ExecuteListInfluenceLedger - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: influence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListInfluenceLedger Use Case
 *
 * DDD: Application use case for list Ledger.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListInfluenceLedgerInput, ListInfluenceLedgerOutput } from "../dto/ledger.dto";
import type { ExecutionContextService, IdGeneratorService } from "@shapemint/services/_shared/index.js";
import type { LedgerRepository } from "../ports";

export class ExecuteListInfluenceLedger {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly ledger: LedgerRepository
  ) {}

  async execute(input: ListInfluenceLedgerInput): Promise<ListInfluenceLedgerOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.infId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.ledger.listInfluenceLedger({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListInfluenceLedgerOutput;
  }
}
