/**
 * PauseMinting handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { pauseMinting } from "@shapemint/api-server/domains/governance/handlers";
import type { GovernanceDDDDependencies } from "@shapemint/api-server/domains/governance";
import { createMintingPause as createMintingPauseEntity } from "@shapemint/factories/governance";
import { createCreateMintingPauseRequest } from "@shapemint/factories/governance";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@shapemint/tests/shared";
import { GOVERNANCE_USE_CASES } from "../__factories__/use-cases.js";

describe("PauseMinting", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: GovernanceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<GovernanceDDDDependencies>(
      GOVERNANCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateMintingPauseRequest();
    const entity = createMintingPauseEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executePauseMinting, "execute").mockResolvedValue(useCaseResult);

    await pauseMinting(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executePauseMinting.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
