/**
 * ListLedger DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: influence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListInfluenceLedgerParams } from "@shapemint/core/influence";

export function createListLedgerRequest(overrides: Partial<ListInfluenceLedgerParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
