/**
 * IncentivePolicy Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { IncentivePolicyEntity } from "@shapemint/core/incentives/models/index.js";
import { incentivesSchemas } from "@shapemint/core/incentives";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "inc";

export function createIncentivePolicy(overrides: Partial<IncentivePolicyEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    bands: overrides.bands ?? [],
    modelId: overrides.modelId ?? `mdl_${ulid().toLowerCase()}`,
    name: overrides.name ?? faker.person.fullName(),
    policyId: overrides.policyId ?? `pol_${ulid().toLowerCase()}`,
    status: overrides.status ?? "draft",
    ...overrides,
  };

  return incentivesSchemas.IncentivePolicy.parse(raw);
}

export function incentivePolicyBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createIncentivePolicy(overrides));
}
