/**
 * Repository interface for Contribution
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: contributions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ContributionEntity
} from "../models/contribution.entity.js";
import type {
  ListContributionsParams,
  ContributionCreateRequest
} from "../types/index.js";
/**
 * ContributionRepository Interface
 */
export interface ContributionRepository extends CreateReadRepository<ContributionEntity, ContributionCreateRequest, string, ListContributionsParams> {

}
