/**
 * VModel DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VModel DTOs
 *
 * DDD: Application DTOs for VModel use cases.
 */

import type { GetModelParams, ListModelsParams, ModelCreateRequest, ModelUpdateRequest, UpdateModelParams } from "@shapemint/core/models/types";

export type ListModelsInput = ListModelsParams;

export type CreateModelInput = ModelCreateRequest;

export type GetModelInput = GetModelParams;

export type UpdateModelInput = UpdateModelParams & ModelUpdateRequest;

export type ListModelsOutput = {};

export type CreateModelOutput = {};

export type GetModelOutput = {};

export type UpdateModelOutput = {};
