/**
 * Reject DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: influence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Reject DTOs
 *
 * DDD: Application DTOs for Reject use cases.
 */

import type { InfluenceRejectRequest, RejectInfluenceParams } from "@shapemint/core/influence/types";

export type RejectInfluenceInput = RejectInfluenceParams & InfluenceRejectRequest;

export type RejectInfluenceOutput = {};
