/**
 * ReproducePack DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: influence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReproducePack DTOs
 *
 * DDD: Application DTOs for ReproducePack use cases.
 */

import type { GetReproducePackParams } from "@shapemint/core/influence/types";

export type GetReproducePackInput = GetReproducePackParams;

export type GetReproducePackOutput = {};
