/**
 * Handlers for Influence
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: influence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { InfluenceDomainModule } from "../dependencies/influence-ddd.dependencies.js";
import type { InfluenceScoreCreateRequest } from "@shapemint/core/influence/types";
import type { GetInfluenceInput, ScoreInfluenceInput } from "@shapemint/services/influence";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/contributions/{contributionId}/influence
 * Operation: getInfluence
 */
export async function getInfluence(
  request: FastifyRequest<{ Params: { contributionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: InfluenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetInfluenceInput = {
    contributionId: request.params.contributionId,
  };
  const result = await deps.useCases.influences.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/contributions/{contributionId}/influence
 * Operation: scoreInfluence
 */
export async function scoreInfluence(
  request: FastifyRequest<{ Params: { contributionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: InfluenceScoreCreateRequest }>,
  reply: FastifyReply,
  deps: InfluenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ScoreInfluenceInput = {
    contributionId: request.params.contributionId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.influences.get.execute(input);
  return reply.code(201).send(result);
}


