/**
 * Handlers for Ledger
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: influence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { InfluenceDomainModule } from "../dependencies/influence-ddd.dependencies.js";
import type { ListInfluenceLedgerInput } from "@shapemint/services/influence";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/influence/ledger
 * Operation: listInfluenceLedger
 */
export async function listInfluenceLedger(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], modelId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: InfluenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListInfluenceLedgerInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.ledgers.list.execute(input);
  return reply.code(200).send(result);
}


