/**
 * Handlers for Reject
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: influence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { InfluenceDomainModule } from "../dependencies/influence-ddd.dependencies.js";
import type { InfluenceRejectRequest } from "@shapemint/core/influence/types";
import type { RejectInfluenceInput } from "@shapemint/services/influence";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/influence/{influenceScoreId}/reject
 * Operation: rejectInfluence
 */
export async function rejectInfluence(
  request: FastifyRequest<{ Params: { influenceScoreId: string }; Querystring: Record<string, string | string[] | undefined>; Body: InfluenceRejectRequest }>,
  reply: FastifyReply,
  deps: InfluenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RejectInfluenceInput = {
    influenceScoreId: request.params.influenceScoreId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.rejects.create.execute(input);
  return reply.code(200).send(result);
}


