/**
 * CreateDraft DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contributions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import { ulid } from "ulid";
import type { ContributionCreateRequest } from "@shapemint/core/contributions";
import { contributionsSchemas } from "@shapemint/core/contributions";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ctr";

export function createCreateDraftRequest(overrides: Partial<ContributionCreateRequest> = {}) {
  const raw = {
    contributorId: overrides.contributorId ?? `usr_${ulid().toLowerCase()}`,
    kind: overrides.kind ?? "model_update",
    modelId: overrides.modelId ?? `mdl_${ulid().toLowerCase()}`,
    policyAccepted: overrides.policyAccepted ?? faker.datatype.boolean(),
    policyId: overrides.policyId ?? `pol_${ulid().toLowerCase()}`,
    privacyMode: overrides.privacyMode ?? faker.datatype.boolean(),
    ...overrides,
  };

  return contributionsSchemas.ContributionCreateRequest.parse(raw);
}
