/**
 * RejectRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: influence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RejectRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RejectRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RejectRepository,
} from "@shapemint/services/influence";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RejectRepositoryDdb } from "./reject-repository.ddb.js";

/**
 * RejectRepositoryAdapter
 *
 * Implements RejectRepository port for infrastructure layer.
 */
export class RejectRepositoryAdapter implements RejectRepository {
  private readonly ddb: RejectRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RejectRepositoryDdb(this.dynamoClient);
  }

  async rejectInfluence(input: Parameters<RejectRepository['rejectInfluence']>[0]): Promise<Awaited<ReturnType<RejectRepository['rejectInfluence']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.rejectInfluence(input);
  }
}
