/**
 * ReproducePackRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: influence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReproducePackRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ReproducePackRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ReproducePackRepository,
} from "@shapemint/services/influence";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ReproducePackRepositoryDdb } from "./reproduce-pack-repository.ddb.js";

/**
 * ReproducePackRepositoryAdapter
 *
 * Implements ReproducePackRepository port for infrastructure layer.
 */
export class ReproducePackRepositoryAdapter implements ReproducePackRepository {
  private readonly ddb: ReproducePackRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ReproducePackRepositoryDdb(this.dynamoClient);
  }

  async getReproducePack(input: Parameters<ReproducePackRepository['getReproducePack']>[0]): Promise<Awaited<ReturnType<ReproducePackRepository['getReproducePack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getReproducePack(input);
  }
}
