/**
 * ContributionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contributions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContributionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ContributionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ContributionRepository,
} from "@shapemint/services/contributions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ContributionRepositoryDdb } from "./contribution-repository.ddb.js";

/**
 * ContributionRepositoryAdapter
 *
 * Implements ContributionRepository port for infrastructure layer.
 */
export class ContributionRepositoryAdapter implements ContributionRepository {
  private readonly ddb: ContributionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ContributionRepositoryDdb(this.dynamoClient);
  }

  async listContributions(input: Parameters<ContributionRepository['listContributions']>[0]): Promise<Awaited<ReturnType<ContributionRepository['listContributions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listContributions(input);
  }

  async submitContribution(input: Parameters<ContributionRepository['submitContribution']>[0]): Promise<Awaited<ReturnType<ContributionRepository['submitContribution']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitContribution(input);
  }

  async getContribution(input: Parameters<ContributionRepository['getContribution']>[0]): Promise<Awaited<ReturnType<ContributionRepository['getContribution']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getContribution(input);
  }
}
