/**
 * DraftRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contributions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DraftRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DraftRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DraftRepository,
} from "@shapemint/services/contributions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DraftRepositoryDdb } from "./draft-repository.ddb.js";

/**
 * DraftRepositoryAdapter
 *
 * Implements DraftRepository port for infrastructure layer.
 */
export class DraftRepositoryAdapter implements DraftRepository {
  private readonly ddb: DraftRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DraftRepositoryDdb(this.dynamoClient);
  }

  async saveContributionDraft(input: Parameters<DraftRepository['saveContributionDraft']>[0]): Promise<Awaited<ReturnType<DraftRepository['saveContributionDraft']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.saveContributionDraft(input);
  }
}
