/**
 * SubmitContribution handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contributions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { submitContribution } from "@shapemint/api-server/domains/contributions/handlers";
import type { ContributionsDDDDependencies } from "@shapemint/api-server/domains/contributions";
import { createContribution as createContributionEntity } from "@shapemint/factories/contributions";
import { createCreateContributionRequest } from "@shapemint/factories/contributions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@shapemint/tests/shared";
import { CONTRIBUTIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("SubmitContribution", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ContributionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ContributionsDDDDependencies>(
      CONTRIBUTIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateContributionRequest();
    const entity = createContributionEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeSubmitContribution, "execute").mockResolvedValue(useCaseResult);

    await submitContribution(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeSubmitContribution.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
