/**
 * TransparencyGrant Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/governance.openapi.types.js";
import { schemas } from "../schemas/governance.schemas.js";

/**
 * Entity: TransparencyGrantEntity
 * Description: Represents the TransparencyGrant domain model.
 * Source: schemas.TransparencyGrant
 * Type: Domain Entity (API)
 */
export const TransparencyGrantEntitySchema = schemas.TransparencyGrant;
export type TransparencyGrantEntity = components["schemas"]["TransparencyGrant"];
