/**
 * BindModel DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocols
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BindModel DTOs
 *
 * DDD: Application DTOs for BindModel use cases.
 */

import type { BindProtocolToModelParams, ProtocolBindRequest } from "@shapemint/core/protocols/types";

export type BindProtocolToModelInput = BindProtocolToModelParams & ProtocolBindRequest;

export type BindProtocolToModelOutput = {};
