/**
 * DownloadRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DownloadRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DownloadRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DownloadRepository,
} from "@shapemint/services/reporting";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DownloadRepositoryDdb } from "./download-repository.ddb.js";

/**
 * DownloadRepositoryAdapter
 *
 * Implements DownloadRepository port for infrastructure layer.
 */
export class DownloadRepositoryAdapter implements DownloadRepository {
  private readonly ddb: DownloadRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DownloadRepositoryDdb(this.dynamoClient);
  }

  async downloadSettlementStatement(input: Parameters<DownloadRepository['downloadSettlementStatement']>[0]): Promise<Awaited<ReturnType<DownloadRepository['downloadSettlementStatement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.downloadSettlementStatement(input);
  }
}
