/**
 * Handlers index
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocols
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./bind-model.handlers.js";
export * from "./deprecate.handlers.js";
export * from "./protocol.handlers.js";
export * from "./publish.handlers.js";
