/**
 * GetSettlementStatement handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getSettlementStatement } from "@shapemint/api-server/domains/incentives/handlers";
import type { IncentivesDDDDependencies } from "@shapemint/api-server/domains/incentives";
import { createSettlementStatement as createSettlementStatementEntity } from "@shapemint/factories/incentives";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@shapemint/tests/shared";
import { INCENTIVES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetSettlementStatement", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: IncentivesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<IncentivesDDDDependencies>(
      INCENTIVES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createSettlementStatementEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetSettlementStatement, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { statementId: entity.id };

    await getSettlementStatement(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetSettlementStatement.execute).toHaveBeenCalledWith(expect.objectContaining({ statementId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { statementId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetSettlementStatement, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getSettlementStatement(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
