/**
 * MintingPause DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MintingPause DTOs
 *
 * DDD: Application DTOs for MintingPause use cases.
 */

import type { ListMintingPausesParams, MintingPauseCreate } from "@shapemint/core/governance/types";

export type PauseMintingInput = MintingPauseCreate;

export type ListMintingPausesInput = ListMintingPausesParams;

export type PauseMintingOutput = {};

export type ListMintingPausesOutput = {};
