/**
 * NegativeInfluence DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * NegativeInfluence DTOs
 *
 * DDD: Application DTOs for NegativeInfluence use cases.
 */

import type { ListNegativeInfluenceRulingsParams, NegativeInfluenceRulingCreate } from "@shapemint/core/governance/types";

export type ListNegativeInfluenceRulingsInput = ListNegativeInfluenceRulingsParams;

export type RuleNegativeInfluenceInput = NegativeInfluenceRulingCreate;

export type ListNegativeInfluenceRulingsOutput = {};

export type RuleNegativeInfluenceOutput = {};
