/**
 * TransparencyGrant DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TransparencyGrant DTOs
 *
 * DDD: Application DTOs for TransparencyGrant use cases.
 */

import type { ListTransparencyGrantsParams, TransparencyGrantCreate } from "@shapemint/core/governance/types";

export type ListTransparencyGrantsInput = ListTransparencyGrantsParams;

export type CreateTransparencyGrantInput = TransparencyGrantCreate;

export type ListTransparencyGrantsOutput = {};

export type CreateTransparencyGrantOutput = {};
