/**
 * ClawbackRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ClawbackRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ClawbackRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ClawbackRepository,
} from "@shapemint/services/incentives";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ClawbackRepositoryDdb } from "./clawback-repository.ddb.js";

/**
 * ClawbackRepositoryAdapter
 *
 * Implements ClawbackRepository port for infrastructure layer.
 */
export class ClawbackRepositoryAdapter implements ClawbackRepository {
  private readonly ddb: ClawbackRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ClawbackRepositoryDdb(this.dynamoClient);
  }

  async clawbackIncentive(input: Parameters<ClawbackRepository['clawbackIncentive']>[0]): Promise<Awaited<ReturnType<ClawbackRepository['clawbackIncentive']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.clawbackIncentive(input);
  }
}
