/**
 * IncentivePolicyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IncentivePolicyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements IncentivePolicyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  IncentivePolicyRepository,
} from "@shapemint/services/incentives";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { IncentivePolicyRepositoryDdb } from "./incentive-policy-repository.ddb.js";

/**
 * IncentivePolicyRepositoryAdapter
 *
 * Implements IncentivePolicyRepository port for infrastructure layer.
 */
export class IncentivePolicyRepositoryAdapter implements IncentivePolicyRepository {
  private readonly ddb: IncentivePolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new IncentivePolicyRepositoryDdb(this.dynamoClient);
  }

  async listIncentivePolicies(input: Parameters<IncentivePolicyRepository['listIncentivePolicies']>[0]): Promise<Awaited<ReturnType<IncentivePolicyRepository['listIncentivePolicies']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listIncentivePolicies(input);
  }

  async createIncentivePolicy(input: Parameters<IncentivePolicyRepository['createIncentivePolicy']>[0]): Promise<Awaited<ReturnType<IncentivePolicyRepository['createIncentivePolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createIncentivePolicy(input);
  }

  async getIncentivePolicy(input: Parameters<IncentivePolicyRepository['getIncentivePolicy']>[0]): Promise<Awaited<ReturnType<IncentivePolicyRepository['getIncentivePolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getIncentivePolicy(input);
  }
}
