/**
 * SettlementStatementRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SettlementStatementRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SettlementStatementRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SettlementStatementRepository,
} from "@shapemint/services/incentives";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SettlementStatementRepositoryDdb } from "./settlement-statement-repository.ddb.js";

/**
 * SettlementStatementRepositoryAdapter
 *
 * Implements SettlementStatementRepository port for infrastructure layer.
 */
export class SettlementStatementRepositoryAdapter implements SettlementStatementRepository {
  private readonly ddb: SettlementStatementRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SettlementStatementRepositoryDdb(this.dynamoClient);
  }

  async listSettlementStatements(input: Parameters<SettlementStatementRepository['listSettlementStatements']>[0]): Promise<Awaited<ReturnType<SettlementStatementRepository['listSettlementStatements']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listSettlementStatements(input);
  }

  async createSettlementStatement(input: Parameters<SettlementStatementRepository['createSettlementStatement']>[0]): Promise<Awaited<ReturnType<SettlementStatementRepository['createSettlementStatement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createSettlementStatement(input);
  }

  async getSettlementStatement(input: Parameters<SettlementStatementRepository['getSettlementStatement']>[0]): Promise<Awaited<ReturnType<SettlementStatementRepository['getSettlementStatement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSettlementStatement(input);
  }
}
