/**
 * ExecuteSaveContributionDraft - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contributions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSaveContributionDraft Use Case
 *
 * DDD: Application use case for get Draft.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SaveContributionDraftInput, SaveContributionDraftOutput } from "../dto/draft.dto";
import type { ExecutionContextService, IdGeneratorService } from "@shapemint/services/_shared/index.js";
import type { DraftRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteSaveContributionDraft {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly draft: DraftRepository
  ) {}

  async execute(input: SaveContributionDraftInput): Promise<SaveContributionDraftOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ctrId();

    // All field names extracted from OpenAPI spec: artefactRef, contributorId, kind, modelId, policyAccepted, policyId, privacyMode
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).contributorId) {
      throw new ValidationError("contributorId is required");
    }
    const contributorId = (input as any).contributorId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.draft.saveContributionDraft({ contributorId: contributorId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${contributorId}`);
    }

    return entity as SaveContributionDraftOutput;
  }
}
