/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contributions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Contributions Domain Use Cases
 * 
 * List of all use case names for the contributions domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const CONTRIBUTIONS_USE_CASES = [
  "executeGetContribution",
  "executeListContributions",
  "executeSaveContributionDraft",
  "executeSubmitContribution"
] as const;
