/**
 * Download DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Download DTOs
 *
 * DDD: Application DTOs for Download use cases.
 */

import type { DownloadSettlementStatementParams } from "@shapemint/core/reporting/types";

export type DownloadSettlementStatementInput = DownloadSettlementStatementParams;

export type DownloadSettlementStatementOutput = {};
