/**
 * MintingPauseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MintingPauseRepository Port
 *
 * DDD: Application port for mintingpauserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListMintingPausesInput, ListMintingPausesOutput, PauseMintingInput, PauseMintingOutput } from "../dto/minting-pause.dto";
export interface MintingPauseRepository {
  pauseMinting(input: PauseMintingInput): Promise<PauseMintingOutput>;
  listMintingPauses(input: ListMintingPausesInput): Promise<ListMintingPausesOutput>;
}

export type { ListMintingPausesInput, ListMintingPausesOutput, PauseMintingInput, PauseMintingOutput } from "../dto/minting-pause.dto";
