/**
 * ResumeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ResumeRepository Port
 *
 * DDD: Application port for resumerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ResumeMintingInput, ResumeMintingOutput } from "../dto/resume.dto";
export interface ResumeRepository {
  resumeMinting(input: ResumeMintingInput): Promise<ResumeMintingOutput>;
}

export type { ResumeMintingInput, ResumeMintingOutput } from "../dto/resume.dto";
