/**
 * ExecuteListNegativeInfluenceRulings - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListNegativeInfluenceRulings Use Case
 *
 * DDD: Application use case for list NegativeInfluence.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListNegativeInfluenceRulingsInput, ListNegativeInfluenceRulingsOutput } from "../dto/negative-influence.dto";
import type { ExecutionContextService, IdGeneratorService } from "@shapemint/services/_shared/index.js";
import type { NegativeInfluenceRepository } from "../ports";

export class ExecuteListNegativeInfluenceRulings {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly negativeInfluence: NegativeInfluenceRepository
  ) {}

  async execute(input: ListNegativeInfluenceRulingsInput): Promise<ListNegativeInfluenceRulingsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.negativeInfluence.listNegativeInfluenceRulings({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListNegativeInfluenceRulingsOutput;
  }
}
