/**
 * InfluenceExportRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InfluenceExportRepository Port
 *
 * DDD: Application port for influenceexportrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ExportInfluenceLedgerInput, ExportInfluenceLedgerOutput } from "../dto/influence-export.dto";
export interface InfluenceExportRepository {
  exportInfluenceLedger(input: ExportInfluenceLedgerInput): Promise<ExportInfluenceLedgerOutput>;
}

export type { ExportInfluenceLedgerInput, ExportInfluenceLedgerOutput } from "../dto/influence-export.dto";
