/**
 * ReproducePack Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: influence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/influence.openapi.types.js";
import { schemas } from "../schemas/influence.schemas.js";

/**
 * Entity: ReproducePackEntity
 * Description: Represents the ReproducePack domain model.
 * Source: schemas.ReproducePack
 * Type: Domain Entity (API)
 */
export const ReproducePackEntitySchema = schemas.ReproducePack;
export type ReproducePackEntity = components["schemas"]["ReproducePack"];
