/**
 * Handlers for Incentive
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { IncentivesDomainModule } from "../dependencies/incentives-ddd.dependencies.js";
import type { IncentiveMintRequest } from "@shapemint/core/incentives/types";
import type { ListIncentivesInput, MintIncentiveInput } from "@shapemint/services/incentives";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/incentives
 * Operation: listIncentives
 */
export async function listIncentives(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: IncentivesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListIncentivesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.incentives.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/incentives
 * Operation: mintIncentive
 */
export async function mintIncentive(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: IncentiveMintRequest }>,
  reply: FastifyReply,
  deps: IncentivesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: MintIncentiveInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.incentives.get.execute(input);
  return reply.code(201).send(result);
}


