/**
 * Handlers for IncentivePolicy
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { IncentivesDomainModule } from "../dependencies/incentives-ddd.dependencies.js";
import type { PolicyCreateRequest } from "@shapemint/core/incentives/types";
import type { CreateIncentivePolicyInput, GetIncentivePolicyInput, ListIncentivePoliciesInput } from "@shapemint/services/incentives";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/incentive-policies
 * Operation: listIncentivePolicies
 */
export async function listIncentivePolicies(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], modelId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: IncentivesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListIncentivePoliciesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.incentivePolicies.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/incentive-policies
 * Operation: createIncentivePolicy
 */
export async function createIncentivePolicy(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: PolicyCreateRequest }>,
  reply: FastifyReply,
  deps: IncentivesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateIncentivePolicyInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.incentivePolicies.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/incentive-policies/{policyId}
 * Operation: getIncentivePolicy
 */
export async function getIncentivePolicy(
  request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: IncentivesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetIncentivePolicyInput = {
    policyId: request.params.policyId,
  };
  const result = await deps.useCases.incentivePolicies.get.execute(input);
  return reply.code(200).send(result);
}


