/**
 * Handlers for SettlementStatement
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { IncentivesDomainModule } from "../dependencies/incentives-ddd.dependencies.js";
import type { StatementCreateRequest } from "@shapemint/core/incentives/types";
import type { CreateSettlementStatementInput, GetSettlementStatementInput, ListSettlementStatementsInput } from "@shapemint/services/incentives";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/settlement-statements
 * Operation: listSettlementStatements
 */
export async function listSettlementStatements(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: IncentivesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListSettlementStatementsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.settlementStatements.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/settlement-statements
 * Operation: createSettlementStatement
 */
export async function createSettlementStatement(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: StatementCreateRequest }>,
  reply: FastifyReply,
  deps: IncentivesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateSettlementStatementInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.settlementStatements.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/settlement-statements/{statementId}
 * Operation: getSettlementStatement
 */
export async function getSettlementStatement(
  request: FastifyRequest<{ Params: { statementId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: IncentivesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetSettlementStatementInput = {
    statementId: request.params.statementId,
  };
  const result = await deps.useCases.settlementStatements.get.execute(input);
  return reply.code(200).send(result);
}


