/**
 * UpdateModel handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updateModel } from "@shapemint/api-server/domains/models/handlers";
import type { ModelsDDDDependencies } from "@shapemint/api-server/domains/models";
import { createUpdateVModelRequest } from "@shapemint/factories/models";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@shapemint/tests/shared";
import { MODELS_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdateModel", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ModelsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ModelsDDDDependencies>(
      MODELS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const input = createUpdateVModelRequest();
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { modelId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdateModel, "execute").mockResolvedValue(useCaseResult);

    await updateModel(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdateModel.execute).toHaveBeenCalledWith(expect.objectContaining({ modelId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
