/**
 * CreateSettlementStatement DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { ulid } from "ulid";
import type { StatementCreateRequest } from "@shapemint/core/incentives";
import { incentivesSchemas } from "@shapemint/core/incentives";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "inc";

export function createCreateSettlementStatementRequest(overrides: Partial<StatementCreateRequest> = {}) {
  const raw = {
    modelId: overrides.modelId ?? `mdl_${ulid().toLowerCase()}`,
    periodEnd: overrides.periodEnd ?? new Date().toISOString(),
    periodStart: overrides.periodStart ?? new Date().toISOString(),
    ...overrides,
  };

  return incentivesSchemas.StatementCreateRequest.parse(raw);
}
