/**
 * Contribution DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contributions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Contribution DTOs
 *
 * DDD: Application DTOs for Contribution use cases.
 */

import type { ContributionCreateRequest, GetContributionParams, ListContributionsParams } from "@shapemint/core/contributions/types";

export type ListContributionsInput = ListContributionsParams;

export type SubmitContributionInput = ContributionCreateRequest;

export type GetContributionInput = GetContributionParams;

export type ListContributionsOutput = {};

export type SubmitContributionOutput = {};

export type GetContributionOutput = {};
