/**
 * Draft DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contributions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Draft DTOs
 *
 * DDD: Application DTOs for Draft use cases.
 */

import type { ContributionCreateRequest } from "@shapemint/core/contributions/types";

export type SaveContributionDraftInput = ContributionCreateRequest;

export type SaveContributionDraftOutput = {};
