/**
 * CreateBindModel DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocols
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { ulid } from "ulid";
import type { ProtocolBindRequest } from "@shapemint/core/protocols";
import { protocolsSchemas } from "@shapemint/core/protocols";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "prt";

export function createCreateBindModelRequest(overrides: Partial<ProtocolBindRequest> = {}) {
  const raw = {
    modelId: overrides.modelId ?? `mdl_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return protocolsSchemas.ProtocolBindRequest.parse(raw);
}
