/**
 * ExecuteCreateProtocol - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocols
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateProtocol Use Case
 *
 * DDD: Application use case for create Protocol.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateProtocolInput, CreateProtocolOutput } from "../dto/protocol.dto";
import type { ExecutionContextService, IdGeneratorService } from "@shapemint/services/_shared/index.js";
import type { ProtocolRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateProtocol {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly protocol: ProtocolRepository
  ) {}

  async execute(input: CreateProtocolInput): Promise<CreateProtocolOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prtId();

    // All field names extracted from OpenAPI spec: inScopeBehaviours, modelId, name, version
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.version) {
      throw new ValidationError("version is required");
    }
    if (!input.modelId) {
      throw new ValidationError("modelId is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.inScopeBehaviours) {
      throw new ValidationError("inScopeBehaviours is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (protocols domain)
    const entityId = this.idGenerator.prtId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.protocol.createProtocol({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateProtocolOutput;
  }
}
