/**
 * GetProtocol handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocols
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getProtocol } from "@shapemint/api-server/domains/protocols/handlers";
import type { ProtocolsDDDDependencies } from "@shapemint/api-server/domains/protocols";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@shapemint/tests/shared";
import { PROTOCOLS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetProtocol", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ProtocolsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ProtocolsDDDDependencies>(
      PROTOCOLS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetProtocol, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { protocolId: entity.id };

    await getProtocol(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetProtocol.execute).toHaveBeenCalledWith(expect.objectContaining({ protocolId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { protocolId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetProtocol, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getProtocol(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
