/**
 * Accept DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Accept DTOs
 *
 * DDD: Application DTOs for Accept use cases.
 */

import type { AcceptIncentivePolicyParams, PolicyAcceptRequest } from "@shapemint/core/incentives/types";

export type AcceptIncentivePolicyInput = AcceptIncentivePolicyParams & PolicyAcceptRequest;

export type AcceptIncentivePolicyOutput = {};
