/**
 * Clawback DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Clawback DTOs
 *
 * DDD: Application DTOs for Clawback use cases.
 */

import type { ClawbackIncentiveParams, ClawbackRequest } from "@shapemint/core/incentives/types";

export type ClawbackIncentiveInput = ClawbackIncentiveParams & ClawbackRequest;

export type ClawbackIncentiveOutput = {};
