/**
 * Routes for Influence
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: influence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getInfluence, scoreInfluence } from "../handlers/influence.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { InfluenceScoreCreateRequest } from "@shapemint/core/influence/types";

// Fastify types are available globally
export async function influenceRoutes(fastify: FastifyInstance) {
  // GET /v1/contributions/{contributionId}/influence (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/contributions/:contributionId/influence",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { contributionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInfluenceDependenciesForRequest();
        await getInfluence(request, reply, deps);
      });
    }
  );


  // POST /v1/contributions/{contributionId}/influence (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/contributions/:contributionId/influence",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { contributionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: InfluenceScoreCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInfluenceDependenciesForRequest();
        await scoreInfluence(request, reply, deps);
      });
    }
  );


}
