/**
 * GetIncentivePolicy DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetIncentivePolicyParams } from "@shapemint/core/incentives";

export function createGetIncentivePolicyRequest(overrides: Partial<GetIncentivePolicyParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
