/**
 * Routes for BindModel
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocols
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { bindProtocolToModel } from "../handlers/bind-model.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { ProtocolBindRequest } from "@shapemint/core/protocols/types";

// Fastify types are available globally
export async function bindModelRoutes(fastify: FastifyInstance) {
  // POST /v1/protocols/{protocolId}/bind-model (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/protocols/:protocolId/bind-model",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { protocolId: string }; Querystring: Record<string, string | string[] | undefined>; Body: ProtocolBindRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProtocolsDependenciesForRequest();
        await bindProtocolToModel(request, reply, deps);
      });
    }
  );


}
