/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocols
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { bindModelRoutes } from "./bind-model.routes.js";
export { deprecateRoutes } from "./deprecate.routes.js";
export { protocolRoutes } from "./protocol.routes.js";
export { publishRoutes } from "./publish.routes.js";
