/**
 * Handlers for Contribution
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contributions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ContributionsDomainModule } from "../dependencies/contributions-ddd.dependencies.js";
import type { ContributionCreateRequest } from "@shapemint/core/contributions/types";
import type { GetContributionInput, ListContributionsInput, SubmitContributionInput } from "@shapemint/services/contributions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/contributions
 * Operation: listContributions
 */
export async function listContributions(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], modelId?: string | string[], status?: string | string[], kind?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ContributionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListContributionsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.contributions.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/contributions
 * Operation: submitContribution
 */
export async function submitContribution(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: ContributionCreateRequest }>,
  reply: FastifyReply,
  deps: ContributionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SubmitContributionInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.contributions.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/contributions/{contributionId}
 * Operation: getContribution
 */
export async function getContribution(
  request: FastifyRequest<{ Params: { contributionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ContributionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetContributionInput = {
    contributionId: request.params.contributionId,
  };
  const result = await deps.useCases.contributions.get.execute(input);
  return reply.code(200).send(result);
}


