/**
 * CreateDeprecate DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocols
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { DeprecateProtocolParams } from "@shapemint/core/protocols";

export function createCreateDeprecateRequest(overrides: Partial<DeprecateProtocolParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
