/**
 * RejectRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: influence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RejectRepository Port
 *
 * DDD: Application port for rejectrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RejectInfluenceInput, RejectInfluenceOutput } from "../dto/reject.dto";
export interface RejectRepository {
  rejectInfluence(input: RejectInfluenceInput): Promise<RejectInfluenceOutput>;
}

export type { RejectInfluenceInput, RejectInfluenceOutput } from "../dto/reject.dto";
