/**
 * ReproducePackRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: influence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReproducePackRepository Port
 *
 * DDD: Application port for reproducepackrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetReproducePackInput, GetReproducePackOutput } from "../dto/reproduce-pack.dto";
export interface ReproducePackRepository {
  getReproducePack(input: GetReproducePackInput): Promise<GetReproducePackOutput>;
}

export type { GetReproducePackInput, GetReproducePackOutput } from "../dto/reproduce-pack.dto";
