/**
 * Handlers for NegativeInfluence
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GovernanceDomainModule } from "../dependencies/governance-ddd.dependencies.js";
import type { NegativeInfluenceRulingCreate } from "@shapemint/core/governance/types";
import type { ListNegativeInfluenceRulingsInput, RuleNegativeInfluenceInput } from "@shapemint/services/governance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/governance/negative-influence
 * Operation: listNegativeInfluenceRulings
 */
export async function listNegativeInfluenceRulings(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], modelId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListNegativeInfluenceRulingsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.negativeInfluences.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/governance/negative-influence
 * Operation: ruleNegativeInfluence
 */
export async function ruleNegativeInfluence(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: NegativeInfluenceRulingCreate }>,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RuleNegativeInfluenceInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.negativeInfluences.get.execute(input);
  return reply.code(201).send(result);
}


