/**
 * Handlers for TransparencyGrant
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GovernanceDomainModule } from "../dependencies/governance-ddd.dependencies.js";
import type { TransparencyGrantCreate } from "@shapemint/core/governance/types";
import type { CreateTransparencyGrantInput, ListTransparencyGrantsInput } from "@shapemint/services/governance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/governance/transparency-grants
 * Operation: listTransparencyGrants
 */
export async function listTransparencyGrants(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], modelId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListTransparencyGrantsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.transparencyGrants.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/governance/transparency-grants
 * Operation: createTransparencyGrant
 */
export async function createTransparencyGrant(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: TransparencyGrantCreate }>,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateTransparencyGrantInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.transparencyGrants.create.execute(input);
  return reply.code(201).send(result);
}


