/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contributions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the contributions domain.
 * Use these factories in tests to create test data.
 */

export { createContribution } from "./contribution/entity/contribution.entity.factory.js";
export { createCreateContributionRequest } from "./contribution/dto/create-contribution.dto.factory.js";
export { createCreateDraftRequest } from "./draft/dto/create-draft.dto.factory.js";
