/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { mintingPauseRoutes } from "./minting-pause.routes.js";
export { negativeInfluenceRoutes } from "./negative-influence.routes.js";
export { transparencyGrantRoutes } from "./transparency-grant.routes.js";
export { resumeRoutes } from "./resume.routes.js";
