/**
 * DeprecateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocols
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeprecateRepository Port
 *
 * DDD: Application port for deprecaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DeprecateProtocolInput, DeprecateProtocolOutput } from "../dto/deprecate.dto";
export interface DeprecateRepository {
  deprecateProtocol(input: DeprecateProtocolInput): Promise<DeprecateProtocolOutput>;
}

export type { DeprecateProtocolInput, DeprecateProtocolOutput } from "../dto/deprecate.dto";
