/**
 * ProtocolRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocols
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProtocolRepository Port
 *
 * DDD: Application port for protocolrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateProtocolInput, CreateProtocolOutput, GetProtocolInput, GetProtocolOutput, ListProtocolsInput, ListProtocolsOutput } from "../dto/protocol.dto";
export interface ProtocolRepository {
  listProtocols(input: ListProtocolsInput): Promise<ListProtocolsOutput>;
  createProtocol(input: CreateProtocolInput): Promise<CreateProtocolOutput>;
  getProtocol(input: GetProtocolInput): Promise<GetProtocolOutput>;
}

export type { CreateProtocolInput, CreateProtocolOutput, GetProtocolInput, GetProtocolOutput, ListProtocolsInput, ListProtocolsOutput } from "../dto/protocol.dto";
