/**
 * Contribution Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contributions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/contributions.openapi.types.js";
import { schemas } from "../schemas/contributions.schemas.js";

/**
 * Entity: ContributionEntity
 * Description: Represents the Contribution domain model.
 * Source: schemas.Contribution
 * Type: Domain Entity (API)
 */
export const ContributionEntitySchema = schemas.Contribution;
export type ContributionEntity = components["schemas"]["Contribution"];
