/**
 * CreateProtocol DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocols
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import { ulid } from "ulid";
import type { ProtocolCreateRequest } from "@shapemint/core/protocols";
import { protocolsSchemas } from "@shapemint/core/protocols";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "prt";

export function createCreateProtocolRequest(overrides: Partial<ProtocolCreateRequest> = {}) {
  const raw = {
    inScopeBehaviours: overrides.inScopeBehaviours ?? [],
    modelId: overrides.modelId ?? `mdl_${ulid().toLowerCase()}`,
    name: overrides.name ?? faker.person.fullName(),
    version: overrides.version ?? faker.lorem.word(),
    ...overrides,
  };

  return protocolsSchemas.ProtocolCreateRequest.parse(raw);
}
