/**
 * ListProtocol DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocols
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListProtocolsParams } from "@shapemint/core/protocols";

export function createListProtocolRequest(overrides: Partial<ListProtocolsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
