/**
 * Routes for Accept
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { acceptIncentivePolicy } from "../handlers/accept.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { PolicyAcceptRequest } from "@shapemint/core/incentives/types";

// Fastify types are available globally
export async function acceptRoutes(fastify: FastifyInstance) {
  // POST /v1/incentive-policies/{policyId}/accept (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/incentive-policies/:policyId/accept",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: PolicyAcceptRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIncentivesDependenciesForRequest();
        await acceptIncentivePolicy(request, reply, deps);
      });
    }
  );


}
