/**
 * Routes for Clawback
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { clawbackIncentive } from "../handlers/clawback.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { ClawbackRequest } from "@shapemint/core/incentives/types";

// Fastify types are available globally
export async function clawbackRoutes(fastify: FastifyInstance) {
  // POST /v1/incentives/{obligationId}/clawback (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/incentives/:obligationId/clawback",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { obligationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: ClawbackRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIncentivesDependenciesForRequest();
        await clawbackIncentive(request, reply, deps);
      });
    }
  );


}
