/**
 * Routes for IncentivePolicy
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createIncentivePolicy, getIncentivePolicy, listIncentivePolicies } from "../handlers/incentive-policy.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { PolicyCreateRequest } from "@shapemint/core/incentives/types";

// Fastify types are available globally
export async function incentivePolicyRoutes(fastify: FastifyInstance) {
  // POST /v1/incentive-policies (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/incentive-policies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: PolicyCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIncentivesDependenciesForRequest();
        await createIncentivePolicy(request, reply, deps);
      });
    }
  );


  // GET /v1/incentive-policies (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/incentive-policies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIncentivesDependenciesForRequest();
        await listIncentivePolicies(request, reply, deps);
      });
    }
  );


  // GET /v1/incentive-policies/{policyId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/incentive-policies/:policyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIncentivesDependenciesForRequest();
        await getIncentivePolicy(request, reply, deps);
      });
    }
  );


}
