/**
 * Routes for Incentive
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listIncentives, mintIncentive } from "../handlers/incentive.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { IncentiveMintRequest } from "@shapemint/core/incentives/types";

// Fastify types are available globally
export async function incentiveRoutes(fastify: FastifyInstance) {
  // GET /v1/incentives (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/incentives",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIncentivesDependenciesForRequest();
        await listIncentives(request, reply, deps);
      });
    }
  );


  // POST /v1/incentives (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/incentives",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: IncentiveMintRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIncentivesDependenciesForRequest();
        await mintIncentive(request, reply, deps);
      });
    }
  );


}
