/**
 * Routes for SettlementStatement
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createSettlementStatement, getSettlementStatement, listSettlementStatements } from "../handlers/settlement-statement.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { StatementCreateRequest } from "@shapemint/core/incentives/types";

// Fastify types are available globally
export async function settlementStatementRoutes(fastify: FastifyInstance) {
  // POST /v1/settlement-statements (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/settlement-statements",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: StatementCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIncentivesDependenciesForRequest();
        await createSettlementStatement(request, reply, deps);
      });
    }
  );


  // GET /v1/settlement-statements (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/settlement-statements",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIncentivesDependenciesForRequest();
        await listSettlementStatements(request, reply, deps);
      });
    }
  );


  // GET /v1/settlement-statements/{statementId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/settlement-statements/:statementId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { statementId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIncentivesDependenciesForRequest();
        await getSettlementStatement(request, reply, deps);
      });
    }
  );


}
