/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./minting-pause-repository.ddb.js";
export * from "./negative-influence-repository.ddb.js";
export * from "./resume-repository.ddb.js";
export * from "./transparency-grant-repository.ddb.js";
export * from "./minting-pause-repository.adapter.js";
export * from "./negative-influence-repository.adapter.js";
export * from "./resume-repository.adapter.js";
export * from "./transparency-grant-repository.adapter.js";
