/**
 * ContributionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contributions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContributionRepository Port
 *
 * DDD: Application port for contributionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetContributionInput, GetContributionOutput, ListContributionsInput, ListContributionsOutput, SubmitContributionInput, SubmitContributionOutput } from "../dto/contribution.dto";
export interface ContributionRepository {
  listContributions(input: ListContributionsInput): Promise<ListContributionsOutput>;
  submitContribution(input: SubmitContributionInput): Promise<SubmitContributionOutput>;
  getContribution(input: GetContributionInput): Promise<GetContributionOutput>;
}

export type { GetContributionInput, GetContributionOutput, ListContributionsInput, ListContributionsOutput, SubmitContributionInput, SubmitContributionOutput } from "../dto/contribution.dto";
