/**
 * ExecuteMintIncentive - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteMintIncentive Use Case
 *
 * DDD: Application use case for get Incentive.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { MintIncentiveInput, MintIncentiveOutput } from "../dto/incentive.dto";
import type { ExecutionContextService, IdGeneratorService } from "@shapemint/services/_shared/index.js";
import type { IncentiveRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteMintIncentive {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly incentive: IncentiveRepository
  ) {}

  async execute(input: MintIncentiveInput): Promise<MintIncentiveOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.incId();

    // All field names extracted from OpenAPI spec: contributionId, influenceScoreId, policyId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).contributionId) {
      throw new ValidationError("contributionId is required");
    }
    const contributionId = (input as any).contributionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.incentive.mintIncentive({ contributionId: contributionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${contributionId}`);
    }

    return entity as MintIncentiveOutput;
  }
}
