/**
 * ExecuteCreateSettlementStatement - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateSettlementStatement Use Case
 *
 * DDD: Application use case for create SettlementStatement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateSettlementStatementInput, CreateSettlementStatementOutput } from "../dto/settlement-statement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@shapemint/services/_shared/index.js";
import type { SettlementStatementRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateSettlementStatement {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly settlementStatement: SettlementStatementRepository
  ) {}

  async execute(input: CreateSettlementStatementInput): Promise<CreateSettlementStatementOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.incId();

    // All field names extracted from OpenAPI spec: modelId, periodEnd, periodStart
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.periodStart) {
      throw new ValidationError("periodStart is required");
    }
    if (!input.modelId) {
      throw new ValidationError("modelId is required");
    }
    if (!input.periodEnd) {
      throw new ValidationError("periodEnd is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (incentives domain)
    const entityId = this.idGenerator.incId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.settlementStatement.createSettlementStatement({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateSettlementStatementOutput;
  }
}
