/**
 * ExecuteClawbackIncentive - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incentives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteClawbackIncentive Use Case
 *
 * DDD: Application use case for get Clawback.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ClawbackIncentiveInput, ClawbackIncentiveOutput } from "../dto/clawback.dto";
import type { ExecutionContextService, IdGeneratorService } from "@shapemint/services/_shared/index.js";
import type { ClawbackRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteClawbackIncentive {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly clawback: ClawbackRepository
  ) {}

  async execute(input: ClawbackIncentiveInput): Promise<ClawbackIncentiveOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.incId();

    // All field names extracted from OpenAPI spec: reason, rulingId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).obligationId) {
      throw new ValidationError("obligationId is required");
    }
    const obligationId = (input as any).obligationId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.clawback.clawbackIncentive({ obligationId: obligationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${obligationId}`);
    }

    return entity as ClawbackIncentiveOutput;
  }
}
